[main]

# No one will be interacting during the build process
assumeno=0
assumeyes=1
defaultyes=1

# Have something that works rather than forced latest, w/o halting the operation
best=0
allow_downgrade=1
allow_vendor_change=1
skip_if_unavailable=1

cacheonly=0
check_config_file_age=1
countme=1
color="auto"
debug_solver=0
debuglevel=0
diskspacecheck=1
enablegroups=1
exit_on_lock=0

# Always use fastest source
fastestmirror=1

# Packages would fail to even run if this check was not present, though FEX translation might be an exception
ignorearch=0

# Weak deps ensure full packages are installed + better potential feature set but huge bloat
# Lets just not remove anything nor add that extra material
clean_requirements_on_remove=0
exclude_from_weak_autodetect=1
install_weak_deps=0

# Online man pages are also present and are infact, easier to navigate.
# A local LLM might as well help you, this might be more deterministic at actual instructions.
# Just use Kiwix in that case.
# tsflags=nodocs

# No bloating the image, cache wont be needed later
keepcache=0
build_cache=0

log_compress=1
log_rotate=6
logfilelevel=0

# This is risky, but we'll keep it for now. Atleast the rest of the transaction should not fail
gpgcheck=0

# This shouldn't have a limit in the first place
max_parallel_downloads=20
throttle=0

metadata_expire=8h
minrate=1
module_obsoletes=1
retries=8
module_stream_switch=1
multilib_policy="best"
obsoletes=1
plugins=1

# No useless kernel protections
autocheck_running_kernel=1
protect_running_kernel=0

# releasever="rawhide" is not used, because some repos do not support it, the ones that do support it have it enabled by default
# We'll use the default value for releasever, provided by Bazzite upstream developers

strict=0

timeout=60
upgrade_group_objects_upgrade=1
zchunk=1
