[main]
allow_downgrade=1
allow_vendor_change=1
assumeno=0
assumeyes=1
autocheck_running_kernel=1
best=0
build_cache=1
cacheonly=0
check_config_file_age=1
clean_requirements_on_remove=1
countme=1
color="always"
debug_solver=0
debuglevel=0
defaultyes=1
diskspacecheck=1
enablegroups=1
exclude_from_weak_autodetect=1
exit_on_lock=0

# Spends 10–30 seconds probing mirrors when the runner's networking is already high-bandwidth
fastestmirror=1

ignorearch=0

# No bloat
install_weak_deps=0

# keepcache=1 is not used because it will bloat the bootc image
# The user won't install packages anyways, so there's no need to keep the cache

log_compress=1
log_rotate=6
logfilelevel=0

# gpgcheck=0 is risky, but we'll keep it excluded for now

max_parallel_downloads=20

# Low to ensure latest contents are available
# Best only for bootc build time
metadata_expire=30m

minrate=1
module_obsoletes=1
retries=8
module_stream_switch=1
multilib_policy="best"
obsoletes=1
plugins=1
protect_running_kernel=1
skip_if_unavailable=1

# WARNING: releasever="rawhide" is not used, because some repos do not support it, the ones that do support it have it enabled by default
# We'll use the default value for releasever, provided by Bazzite upstream developers

strict=0
throttle=0
timeout=60
upgrade_group_objects_upgrade=1
zchunk=1
