[main]

# Auto-agree
assumeno=0
assumeyes=1
defaultyes=1

# Opportunistic continuity w/o halting operation
best=0
strict=0
allow_downgrade=1
allow_vendor_change=1
skip_if_unavailable=1

countme=1
enablegroups=1
exit_on_lock=0

# Always use fastest source
fastestmirror=1

# Packages would fail to even run if this check was not present, though FEX translation might be an exception
ignorearch=0

# Weak deps ensure full packages are installed + better potential feature set but huge bloat
# Lets just not remove anything nor add that extra material
clean_requirements_on_remove=1
exclude_from_weak_autodetect=1
install_weak_deps=0

# No bloating the image
keepcache=0
cacheonly=0
build_cache=0
tsflags=nodocs

# Logging
log_compress=1
log_rotate=6
logfilelevel=0
rpmverbosity=warn
color="auto"
debug_solver=0
debuglevel=0

# Verification - transactions, file fetches, protections
gpgcheck=1
diskspacecheck=1
check_config_file_age=1

# No download limits
max_parallel_downloads=20
throttle=0

metadata_expire=6h
module_obsoletes=1
retries=8
module_stream_switch=1
multilib_policy="best"
obsoletes=1
plugins=1

# Kernel protections disabled
autocheck_running_kernel=1
protect_running_kernel=0

# releasever="rawhide" is not used, because some repos do not support it, the ones that do support it have it enabled by default
# We'll use the default value for releasever, provided by Bazzite upstream developers

timeout=60
upgrade_group_objects_upgrade=1
zchunk=1
